/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.vista;

import controlador.ControladorEstudiante;
import datos.modelo.Estudiante;
import java.awt.Color;
import java.util.List;
import javax.swing.table.TableModel;

/**
 *
 * @author Yorman Aguirre
 */
public class ViewEstudiante extends javax.swing.JFrame {
    
    private final ControladorEstudiante controladorEstudiante;
    /**
     * Creates new form ViewEstudiante
     */
    public ViewEstudiante() {
        initComponents();
        controladorEstudiante = new ControladorEstudiante();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablaEstudiantes = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        estudiantesInfo = new javax.swing.JTable();
        tituloListarEstudiantes = new javax.swing.JLabel();
        line2 = new javax.swing.JLabel();
        line1 = new javax.swing.JLabel();
        tituloAdministración = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtFecha = new javax.swing.JFormattedTextField();
        lblApellidos = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtMensaje = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        tablaEstudiantes.setMinimumSize(new java.awt.Dimension(500, 500));
        tablaEstudiantes.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        estudiantesInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Apellidos", "Fecha Nacimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        estudiantesInfo.setCellSelectionEnabled(true);
        estudiantesInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estudiantesInfoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(estudiantesInfo);
        estudiantesInfo.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        tablaEstudiantes.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 250));

        tituloListarEstudiantes.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        tituloListarEstudiantes.setText("Lista de estudiantes registrados");
        tablaEstudiantes.getContentPane().add(tituloListarEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        line2.setText("__________________________________________________________________");
        tablaEstudiantes.getContentPane().add(line2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        line1.setText("_______________________________________________________________________________________________________");
        line1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        tituloAdministración.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        tituloAdministración.setText("ADMINISTRACIÓN DE ESTUDIANTES");
        tituloAdministración.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnGuardar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardar(evt);
            }
        });

        btnListar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListar(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lblNombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblNombre.setText("Nombre:");

        txtNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre.setText("Ingrese el nombre ");
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });

        txtApellidos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtApellidos.setForeground(new java.awt.Color(153, 153, 153));
        txtApellidos.setText("Ingrese apellidos");
        txtApellidos.setToolTipText("");
        txtApellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidosMouseClicked(evt);
            }
        });

        txtFecha.setForeground(new java.awt.Color(153, 153, 153));
        txtFecha.setText("AAAA-MM-DD");
        txtFecha.setToolTipText("");
        txtFecha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFechaMouseClicked(evt);
            }
        });

        lblApellidos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblApellidos.setText("Apellidos:");

        lblFecha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblFecha.setText("Fecha de nacimiento:");

        lblCodigo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblCodigo.setText("Código:");

        txtCodigo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtCodigo.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCodigo)
                    .addComponent(lblNombre)
                    .addComponent(lblApellidos)
                    .addComponent(lblFecha))
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtApellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblApellidos)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(27, 27, 27))
        );

        txtNombre.getAccessibleContext().setAccessibleName("txtNombre");
        txtFecha.getAccessibleContext().setAccessibleName("");

        txtMensaje.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        btnActualizar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setEnabled(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizar(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminar(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(line1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(tituloAdministración))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMensaje))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloAdministración)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(line1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMensaje)
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardar
        
        Estudiante estudiante = new Estudiante(txtNombre.getText(), txtApellidos.getText(), txtFecha.getText());
        if(controladorEstudiante.registrar(estudiante)){
            txtMensaje.setForeground(Color.GREEN);
            txtMensaje.setText("Se ha registrado EXITOSAMENTE");
        }else{
            txtMensaje.setForeground(Color.RED);
            txtMensaje.setText("No se logro registrar el estudiante");
        }
        txtNombre.setText(" ");
        txtApellidos.setText(" ");
        txtFecha.setText(" ");
    }//GEN-LAST:event_botonGuardar

    private void txtFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaMouseClicked
        txtFecha.setText(" ");
        txtFecha.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtFechaMouseClicked

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        txtNombre.setText(" ");
        txtNombre.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtApellidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidosMouseClicked
        txtApellidos.setText(" ");
        txtApellidos.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtApellidosMouseClicked

    private void botonListar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListar
        tablaEstudiantes.setVisible(true);
        List<Estudiante> estudiantes = controladorEstudiante.verEstudiantes();
        estudiantesInfo.setEditingColumn(4);
        estudiantesInfo.setEditingRow(estudiantes.size());
        estudiantesInfo.setValueAt("Código", 0, 0);
        estudiantesInfo.setValueAt("Nombre", 0, 1);
        estudiantesInfo.setValueAt("Apellidos", 0, 2);
        estudiantesInfo.setValueAt("Fecha Nacimiento", 0, 3);
        int fila = 0;
        for(Estudiante estudiante : estudiantes){
            estudiantesInfo.setValueAt(estudiante.getCodigo(),fila , 0);
            estudiantesInfo.setValueAt(estudiante.getNombre(),fila , 1);
            estudiantesInfo.setValueAt(estudiante.getApellidos(),fila , 2);
            estudiantesInfo.setValueAt(estudiante.getFechaNacimiento(),fila , 3);
            fila++;
        }
    }//GEN-LAST:event_botonListar

    private void estudiantesInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estudiantesInfoMouseClicked
        int row = estudiantesInfo.getSelectedRow();
        TableModel tableModel = estudiantesInfo.getModel();
        Estudiante estudiante = new Estudiante();
        estudiante.setCodigo((long) tableModel.getValueAt(row, 0));
        estudiante.setNombre((String) tableModel.getValueAt(row,1));
        estudiante.setApellidos((String) tableModel.getValueAt(row, 2));
        estudiante.setFechaNacimiento((String) tableModel.getValueAt(row, 3));
        
        txtCodigo.setForeground(Color.BLACK);
        txtCodigo.setText(Long.toString(estudiante.getCodigo()));
        txtNombre.setForeground(Color.BLACK);
        txtNombre.setText(estudiante.getNombre());
        txtApellidos.setForeground(Color.BLACK);
        txtApellidos.setText(estudiante.getApellidos());
        txtFecha.setForeground(Color.BLACK);
        txtFecha.setText(estudiante.getFechaNacimiento());
        tablaEstudiantes.setVisible(false);
        
        btnActualizar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnGuardar.setEnabled(false);
    }//GEN-LAST:event_estudiantesInfoMouseClicked

    private void botonActualizar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizar
        Estudiante estudiante = new Estudiante(txtNombre.getText(), txtApellidos.getText(), txtFecha.getText());
        estudiante.setCodigo(Long.parseLong(txtCodigo.getText()));
        if(controladorEstudiante.actualizar(estudiante)){
            txtMensaje.setForeground(Color.GREEN);
            txtMensaje.setText("Se ha Actualizado EXITOSAMENTE");
        }else{
            txtMensaje.setForeground(Color.RED);
            txtMensaje.setText("No se logro registrar el estudiante");
        }
        txtNombre.setText(" ");
        txtApellidos.setText(" ");
        txtFecha.setText(" ");
        txtCodigo.setText(" ");
        
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnGuardar.setEnabled(true);
    }//GEN-LAST:event_botonActualizar

    private void botonEliminar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminar
        Estudiante estudiante = new Estudiante(txtNombre.getText(), txtApellidos.getText(), txtFecha.getText());
        estudiante.setCodigo(Long.parseLong(txtCodigo.getText()));
        if(controladorEstudiante.eliminar(estudiante)){
            txtMensaje.setForeground(Color.GREEN);
            txtMensaje.setText("Se ha Eliminado EXITOSAMENTE");
        }else{
            txtMensaje.setForeground(Color.RED);
            txtMensaje.setText("No se logro registrar el estudiante");
        }
        txtNombre.setText(" ");
        txtApellidos.setText(" ");
        txtFecha.setText(" ");
        txtCodigo.setText(" ");
        
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnGuardar.setEnabled(true);
    }//GEN-LAST:event_botonEliminar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnListar;
    private javax.swing.JTable estudiantesInfo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel line1;
    private javax.swing.JLabel line2;
    private javax.swing.JFrame tablaEstudiantes;
    private javax.swing.JLabel tituloAdministración;
    private javax.swing.JLabel tituloListarEstudiantes;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JLabel txtMensaje;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
